basePath: /api
definitions:
  dto.Message:
    properties:
      data: {}
      message:
        type: string
    type: object
  dto.MessageError:
    properties:
      message:
        type: string
    type: object
  dto.Task:
    properties:
      description:
        example: Comprender la arquitectura hexagonal
        type: string
      id:
        type: integer
      name:
        example: Estudiar Go
        type: string
      puntuation:
        example: 2
        maximum: 10
        minimum: 1
        type: integer
    required:
    - description
    - name
    - puntuation
    type: object
host: localhost:3005
info:
  contact:
    email: kiven.acv2@gmail.com
    name: Kiven Acevedo
  description: Tasks Manager.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Tasks API
  version: "1.0"
paths:
  /tasks:
    get:
      consumes:
      - application/json
      description: return all tasks
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.Message'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.MessageError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.MessageError'
      summary: Get all tasks
      tags:
      - Tasks
    post:
      consumes:
      - application/json
      description: return new tasks
      parameters:
      - description: Task
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/dto.Task'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.MessageError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.MessageError'
      summary: Add task
      tags:
      - Tasks
  /tasks/{id}:
    delete:
      consumes:
      - application/json
      description: return void
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.MessageError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.MessageError'
      summary: Deleted Task By ID
      tags:
      - Tasks
    get:
      consumes:
      - application/json
      description: return Find Task By ID
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.MessageError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.MessageError'
      summary: Find Task By ID
      tags:
      - Tasks
    put:
      consumes:
      - application/json
      description: return Update Task By ID
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: integer
      - description: Task
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/dto.Task'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.MessageError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.MessageError'
      summary: Update Task By ID
      tags:
      - Tasks
swagger: "2.0"
